# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHB():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hB(self):
    # Test name: HB
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.humblebundle.com/")
    # 2 | setWindowSize | 1420x1140 | 
    self.driver.set_window_size(1420, 1140)
    # 3 | click | css=.navbar-item > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-item > img").click()
    # 4 | click | css=.secondary-caret | 
    self.driver.find_element(By.CSS_SELECTOR, ".secondary-caret").click()
    # 5 | click | linkText=Einkäufe | 
    self.driver.find_element(By.LINK_TEXT, "Einkäufe").click()
  
